APP_NAME=ose-postman
DOCKER_IMAGE=$(APP_NAME):latest

.PHONY: build run clean

build:
	docker build -t $(DOCKER_IMAGE) .

run:
	docker run --rm \
		-e APP_ENV \
		-e APP_SERVICE_NAME \
		-e APP_SERVICE_LOGGER_ENVIRONMENT \
		-e APP_SERVICE_LOGGER_LEVEL \
		-e APP_SERVICE_TRACER_ENDPOINT \
		-e APP_SERVICE_TRACER_SERVICE_NAME \
		-e APP_SERVICE_TRACER_SAMPLE_RATIO \
		-e APP_BUS_ADDRESS \
		-e APP_GRPC_PORT \
		-e APP_POSTGRES_HOST \
		-e APP_POSTGRES_PORT \
		-e APP_POSTGRES_USER \
		-e APP_POSTGRES_DATABASE \
		-e APP_POSTGRES_PASSWORD \
		-e APP_POSTGRES_SSLMODE \
		-e APP_MAILER_HOST \
		-e APP_MAILER_USERNAME \
		-e APP_MAILER_PASSWORD \
		-e APP_MAILER_PORT \
		-e APP_MONGO_HOST \
		-e APP_MONGO_PORT \
		-e APP_MONGO_TIMEOUT \
		-e APP_MONGO_USER \
		-e APP_MONGO_PASSWORD \
		-e APP_MONGO_DATABASE \
		$(DOCKER_IMAGE)

clean:
	docker rmi $(DOCKER_IMAGE)
